spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher