version: "3.9"
services:

  postgres:
    container_name: platform
    image: 'postgres:latest'
    command: postgres -c 'max_connections=500'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      -  './postgres/volume:/var/lib/postgresql/'